title: Web and Mobile App Software Development Reading London
email: hq@logicroom.co
name : Logic Room

env: development

description: > # this means to ignore newlines until "baseurl:"
  Web and Mobile Sofware Reading, Berkshire
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.logicroom.co
twitter_username: jekyllrb
github_username:  jekyll
permalink: /:title/

include: [_redirects,resources]

collections:
- my_collection

# Build settings
markdown: kramdown
theme: minima
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

#sitemap:
#  filename: "/sitemaps.xml"
#  exclude:
#      - "/assets/main.scss"
#      - "/web-application-development-company-lp"
#      - "/hire-javascript-developers-uk"
#      - "/services/javascript-development-reading-berkshire/"
#      - "/services/mobile-app-development-reading-berkshire"
#  include_posts:
#      - "/index.html"
#  change_frequency_name: "change_frequency"
#  priority_name: "priority"

sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/assets/css/main.css"
        - "/web-application-development-company-lp/index.html"
        - "/web-application-development-company-lp/thank-you/index.html"
        - "/react-native-development-company-lp/index.html"
        - "/react-native-development-company-lp/thank-you/index.html"
        - "/services/web-application-development-reading-berkshire/thank-you/index.html"

        - "/services/javascript-development-reading-berkshire/index.html"
        - "/services/mobile-app-development-reading-berkshire/index.html"
        - "/framework/index.html"
        - "/contact/thank-you/index.html"

    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"



gems:
  - jekyll-feed
  - octopress-minify-html
exclude:
  - Gemfile
  - Gemfile.lock

