#-------------------------------------------
# Testimonials section
testimonials:
- {image: 'testimonials/james_mcnally.jpg',
  name: 'James McNally',
  description: '(Engineer/Director - Wiresmith Technology)',
  content: '<h5>"Logic Room produced high quality code whilst still maintaining productivity and I am more than happy to maintain the code they will be leaving, as it is well written and well tested. I hope we can work together again in the future."</h5>'}
- {image: 'testimonials/james_whelan.jpg',
  name: 'James Whelan',
  description: '(Managing Director - Faircare Solutions)',
  content: '<h5>"For our modular employee engagement platform MyWorkPal, Logic Room provided consultancy around building responsive Single Page Applications, Agile Methodologies and Continuous integration. The result was fully aligned with its modular architecture, with its continued reliability and scalability being a credit to the team"</h5>'}
- {image: 'testimonials/kieran_gutteridge.jpg',
  name: 'Kieran Gutteridge',
  description: '(CTO - Intohand)',
  content: '<h5>"Logic Room provided enthusiasm and commitment. They helped us drive higher code quality on one of our projects at Intohand by using TDD and Agile. They are passionate about what they do and are willing to coach anyone who is involved on the project so that they are all striving for the same "Clean Code" goal!"</h5>'}

#-------------------------------------------
# Works section
works:
- {content_first: '<p class="text-white">dings on all of my boards, a permanent salt water/urine stench in my wetsuit, and a giant grin from ear to ear. This is the beautiful state of being completely surfed out in Peru.</p>',
  content_second: '<p class="text-white">While we all felt that Travis was a great asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  project_first: '<p class="text-white">Project code quality and architecture</p>',
  project_second: '<p class="text-white">Ensuring enough specification and estimation is complete</p>',
  project_third: '<p class="text-white">Tracking and keeping the client aware of progress</p>',
  project_fourth: '<p class="text-white">Supporting The Development Team</p>',
  content_third: '<p class="text-white">Seasoned programmers with years of industry experience, our leaders undergo extensive traning and mentorship in cutting edge technical disciplines, management and people skills. This given them an unrivalled advantage dealing with complex organisations and environments.</p>',
  content_fourth: '<p class="text-white">Any of our training and code reviews are also carried out by one of our technical leaders.</p>'}

#-------------------------------------------
# footer section
footers:
- {phone: '<p>Phone 07889 812 612</p>',
  email: '<p>E-mail hq@logicroom.co</p>',
  location: '<p>85A Westbourne Terrace <br>Reading <br> RG30 2RP</p>',
  company: '<p>Registered Company: 7872364</p>'}
